### ISSUE TITLE
[Bug Report] traceback when using Hirsute final beta image

### ISSUE THREAD

**Issue by tai271828** [dannf/ubuntu-server-netboot#14]
## Description

Ubuntu 20.04 shows

```
~/ubuntu-server-netboot$ ./ubuntu-server-netboot.py --url https://cdimage.ubuntu.com/daily-live/current/hirsute-desktop-arm64.iso
INFO: Downloading https://cdimage.ubuntu.com/daily-live/current/hirsute-desktop-arm64.iso
Traceback (most recent call last):
  File "./ubuntu-server-netboot.py", line 218, in <module>
    iso = ServerLiveIso(iso.name)
  File "./ubuntu-server-netboot.py", line 67, in __init__
    raise Exception(
Exception: /tmp/tmp7tk0kw8t does not look like an Ubuntu Server ISO
```

## Expected Behavior

ubuntu-server-netboot.py begin to extract files from ISO

## More Information
By using iso cache, it shows the same trace error message:
```
$ ./ubuntu-server-netboot.py --url https://cdimage.ubuntu.com/daily-live/current/hirsute-desktop-arm64.iso --iso ~/hirsute-desktop-arm64.iso
Traceback (most recent call last):
  File "./ubuntu-server-netboot.py", line 211, in <module>
    iso = ServerLiveIso(args.iso)
  File "./ubuntu-server-netboot.py", line 67, in __init__
    raise Exception(
Exception: /home/ubuntu/hirsute-desktop-arm64.iso does not look like an Ubuntu Server ISO
```

However `isoinfo` shows its iso metadata:

```
$ isoinfo -d -i hirsute-desktop-arm64.iso 
CD-ROM is in ISO 9660 format
System id: 
Volume id: Ubuntu 21.04 arm64
Volume set id: 
Publisher id: 
Data preparer id: XORRISO-1.5.2 2019.10.26.180001, LIBISOBURN-1.5.2, LIBISOFS-1.5.2, LIBBURN-1.5.2
Application id: 
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 1114262
El Torito VD version 1 found, boot catalog is in sector 210
Joliet with UCS level 3 found
Rock Ridge signatures version 1 found
Eltorito validation header:
    Hid 1
    Arch 239 (Unknown Arch)
    ID ''
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 0
        Sys type 0
        Nsect 2200
        Bootoff 10F780 1111936
```

**Comment by dannf** [comment]
Thanks for the report @tai271828 ! Note that this tool is only intended to work with server ISOs, so a failure with a desktop ISO is not unexpected.

**Comment by tai271828** [comment]
Oooops, I must be tired today. Sorry for spamming!
